# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50bdc521b33cabbfbdffcd2ac8947dc8c5230a030de61a91cb5a068672db13f9f369c458ce2ec78d6ce5367703edfa17fcf158abb6fa271acc24cf6f124c191b

test:
  secret_key_base: 140dd4aedfac141022c97a2078d99a20861056614c31df515d0ef41f2e230eaa170d19cc5fdfbde458a3b2344d4d510648497e1bc2bcfe84239b2c27a339a67c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
